### ISSUE TITLE
Doesn't build with rgbds v0.4.2

### ISSUE THREAD

**Issue by basxto** [DevEd2/FXHammer-Disasm#2]
```
warning: main.asm(9): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(11): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(12): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(13): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(14): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(15): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(16): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(18): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(735): [-Wobsolete]
    Non-local labels without a colon are deprecated
warning: main.asm(844) -> FXHammer.asm(5): [-Wobsolete]
    Non-local labels without a colon are deprecated
error: main.asm(844) -> FXHammer.asm(180): Unknown symbol "FXHammer_RAM3"
Linking failed with 1 error
error: Error opening file FXHammer.gb: No such file or directory
```

**Comment by DevEd2** [comment]
Sorry for the late response...

This whole project is in dire need of a refactor. Will look into it once I have some free time.

**Comment by basxto** [comment]
No problem.
I was just  playing around with it. I'd like to use this at some point, but that also won't happen that soon.
Is it meant to use only the default sounds? Or is there a way of generating/converting those sounds?

And in case this is more than just a disassembly, that should maybe be stated. (like permitted release of disassembly because original sources were lost or something like this)

**Comment by basxto** [comment]
> Is it meant to use only the default sounds? Or is there a way of generating/converting those sounds?

Editor can be found here https://www.pouet.net/prod.php?which=17337
