### ISSUE TITLE
Player_Initialize is missing

### ISSUE THREAD

**Issue by basxto** [DevEd2/FXHammer-Disasm#5]
> Initializes hardware sound registers and player variables at $c7c0-$c7ef. Call this at program startup before using any other Carillon Player or FX Hammer routines.

**Comment by DevEd2** [comment]
Player_Initialize is part of Carillon Editor, not FX Hammer, and as such is not included as part of this disassembly.

**Comment by basxto** [comment]
That’s true, it’s not part of the sound bank. But FX Hammer assumes that everything was initialized, so I think we should add the part that is relevant for initializing FX Hammer.
